image: fedora:latest

before_script:
  - >
    dnf install 'dnf-command(copr)' git libtool make libasan
    python3 python3-six python3-pyparsing glib-networking
    meson ninja-build gdk-pixbuf2-devel
    -y
  - dnf copr enable @spice/nightly -y
  - dnf builddep spice -y

makecheck:
  script:
  - >
    CFLAGS='-O2 -pipe -g -fsanitize=address -fno-omit-frame-pointer -Wframe-larger-than=40920'
    LDFLAGS='-fsanitize=address -lasan'
    ./autogen.sh --enable-extra-checks --enable-celt051
  - make
  - make check || (cat tests/test-suite.log && exit 1)

meson-makecheck:
  script:
  - >
    CFLAGS='-O2 -pipe -g -fsanitize=address -fno-omit-frame-pointer -Wframe-larger-than=40920'
    LDFLAGS='-fsanitize=address -lasan'
    meson build -Dextra-checks=true -Dcelt051=true || (cat build/meson-logs/meson-log.txt && exit 1)
  - ninja -C build
  - (cd build && meson test) || (cat build/meson-logs/testlog.txt && exit 1)
